-- Walmart Business Problems

-- 1. Find different payment method and number of transactions, number of qty sold
-- 2. Identify the highest-rated category in each branch, displaying the branch, category AVG RATING
-- 3. Identify the busiest day for each branch based on the number of transactions
-- 4. Calculate the total quantity of items sold per payment method. List payment_method and total_quantity.
-- 5. Determine the average, minimum, and maximum rating of category for each city. List the city, average_raling, min_rating, and max_rating.
-- 6. Calculate the total profit for each category by considering total_profit as (unit_price quantity profit_margin). 
-- 	  List category and total_profit, ordered from highest to lowest profit.
-- 7. Determine the most common payment method for each Branch. Display Branch and the preferred_payment_method.
-- 8. Categorize sates into 3 group MORNING, AFTERNOON, EVENING. Find out each of the shift and number of invoices
-- 9. Identify 5 branch with highest decrese ratio in revevenue compare to last year (current year 2023 and last year 2022)